/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FacultyMember {
  'id' : bigint,
  'bio' : string,
  'name' : string,
  'designation' : string,
  'department' : string,
  'qualification' : string,
}
export interface NewsEvent {
  'id' : bigint,
  'title' : string,
  'date' : Timestamp,
  'description' : string,
  'isActive' : boolean,
  'category' : NewsEventCategory,
}
export type NewsEventCategory = { 'news' : null } |
  { 'event' : null };
export interface Program {
  'id' : bigint,
  'duration' : string,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'eligibility' : string,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'addFacultyMember' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'addNewsEvent' : ActorMethod<
    [string, string, NewsEventCategory, boolean],
    undefined
  >,
  'addProgram' : ActorMethod<
    [string, string, string, string, boolean],
    undefined
  >,
  'getActiveNewsEvents' : ActorMethod<[], Array<NewsEvent>>,
  'getActivePrograms' : ActorMethod<[], Array<Program>>,
  'getAllFacultyMembers' : ActorMethod<[], Array<FacultyMember>>,
  'getAllNewsEvents' : ActorMethod<[], Array<NewsEvent>>,
  'getAllPrograms' : ActorMethod<[], Array<Program>>,
  'getFacultyMember' : ActorMethod<[bigint], FacultyMember>,
  'getNewsEvent' : ActorMethod<[bigint], NewsEvent>,
  'getProgram' : ActorMethod<[bigint], Program>,
  'removeFacultyMember' : ActorMethod<[bigint], undefined>,
  'removeNewsEvent' : ActorMethod<[bigint], undefined>,
  'removeProgram' : ActorMethod<[bigint], undefined>,
  'submitAdmissionInquiry' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'submitContactForm' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'updateFacultyMember' : ActorMethod<
    [bigint, string, string, string, string, string],
    undefined
  >,
  'updateNewsEvent' : ActorMethod<
    [bigint, string, string, NewsEventCategory, boolean],
    undefined
  >,
  'updateProgram' : ActorMethod<
    [bigint, string, string, string, string, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];