/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const NewsEventCategory = IDL.Variant({
  'news' : IDL.Null,
  'event' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const NewsEvent = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : Timestamp,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'category' : NewsEventCategory,
});
export const Program = IDL.Record({
  'id' : IDL.Nat,
  'duration' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'eligibility' : IDL.Text,
});
export const FacultyMember = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'designation' : IDL.Text,
  'department' : IDL.Text,
  'qualification' : IDL.Text,
});

export const idlService = IDL.Service({
  'addFacultyMember' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addNewsEvent' : IDL.Func(
      [IDL.Text, IDL.Text, NewsEventCategory, IDL.Bool],
      [],
      [],
    ),
  'addProgram' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'getActiveNewsEvents' : IDL.Func([], [IDL.Vec(NewsEvent)], ['query']),
  'getActivePrograms' : IDL.Func([], [IDL.Vec(Program)], ['query']),
  'getAllFacultyMembers' : IDL.Func([], [IDL.Vec(FacultyMember)], ['query']),
  'getAllNewsEvents' : IDL.Func([], [IDL.Vec(NewsEvent)], ['query']),
  'getAllPrograms' : IDL.Func([], [IDL.Vec(Program)], ['query']),
  'getFacultyMember' : IDL.Func([IDL.Nat], [FacultyMember], ['query']),
  'getNewsEvent' : IDL.Func([IDL.Nat], [NewsEvent], ['query']),
  'getProgram' : IDL.Func([IDL.Nat], [Program], ['query']),
  'removeFacultyMember' : IDL.Func([IDL.Nat], [], []),
  'removeNewsEvent' : IDL.Func([IDL.Nat], [], []),
  'removeProgram' : IDL.Func([IDL.Nat], [], []),
  'submitAdmissionInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateFacultyMember' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateNewsEvent' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, NewsEventCategory, IDL.Bool],
      [],
      [],
    ),
  'updateProgram' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const NewsEventCategory = IDL.Variant({
    'news' : IDL.Null,
    'event' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const NewsEvent = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : Timestamp,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'category' : NewsEventCategory,
  });
  const Program = IDL.Record({
    'id' : IDL.Nat,
    'duration' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'eligibility' : IDL.Text,
  });
  const FacultyMember = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'designation' : IDL.Text,
    'department' : IDL.Text,
    'qualification' : IDL.Text,
  });
  
  return IDL.Service({
    'addFacultyMember' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addNewsEvent' : IDL.Func(
        [IDL.Text, IDL.Text, NewsEventCategory, IDL.Bool],
        [],
        [],
      ),
    'addProgram' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'getActiveNewsEvents' : IDL.Func([], [IDL.Vec(NewsEvent)], ['query']),
    'getActivePrograms' : IDL.Func([], [IDL.Vec(Program)], ['query']),
    'getAllFacultyMembers' : IDL.Func([], [IDL.Vec(FacultyMember)], ['query']),
    'getAllNewsEvents' : IDL.Func([], [IDL.Vec(NewsEvent)], ['query']),
    'getAllPrograms' : IDL.Func([], [IDL.Vec(Program)], ['query']),
    'getFacultyMember' : IDL.Func([IDL.Nat], [FacultyMember], ['query']),
    'getNewsEvent' : IDL.Func([IDL.Nat], [NewsEvent], ['query']),
    'getProgram' : IDL.Func([IDL.Nat], [Program], ['query']),
    'removeFacultyMember' : IDL.Func([IDL.Nat], [], []),
    'removeNewsEvent' : IDL.Func([IDL.Nat], [], []),
    'removeProgram' : IDL.Func([IDL.Nat], [], []),
    'submitAdmissionInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateFacultyMember' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateNewsEvent' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, NewsEventCategory, IDL.Bool],
        [],
        [],
      ),
    'updateProgram' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };