/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Program {
    id: bigint;
    duration: string;
    name: string;
    description: string;
    isActive: boolean;
    eligibility: string;
}
export interface FacultyMember {
    id: bigint;
    bio: string;
    name: string;
    designation: string;
    department: string;
    qualification: string;
}
export type Timestamp = bigint;
export interface NewsEvent {
    id: bigint;
    title: string;
    date: Timestamp;
    description: string;
    isActive: boolean;
    category: NewsEventCategory;
}
export enum NewsEventCategory {
    news = "news",
    event = "event"
}
export interface backendInterface {
    addFacultyMember(name: string, designation: string, qualification: string, department: string, bio: string): Promise<void>;
    addNewsEvent(title: string, description: string, category: NewsEventCategory, isActive: boolean): Promise<void>;
    addProgram(name: string, duration: string, description: string, eligibility: string, isActive: boolean): Promise<void>;
    getActiveNewsEvents(): Promise<Array<NewsEvent>>;
    getActivePrograms(): Promise<Array<Program>>;
    getAllFacultyMembers(): Promise<Array<FacultyMember>>;
    getAllNewsEvents(): Promise<Array<NewsEvent>>;
    getAllPrograms(): Promise<Array<Program>>;
    getFacultyMember(id: bigint): Promise<FacultyMember>;
    getNewsEvent(id: bigint): Promise<NewsEvent>;
    getProgram(id: bigint): Promise<Program>;
    removeFacultyMember(id: bigint): Promise<void>;
    removeNewsEvent(id: bigint): Promise<void>;
    removeProgram(id: bigint): Promise<void>;
    submitAdmissionInquiry(applicantName: string, email: string, phone: string, programOfInterest: string, academicBackground: string): Promise<void>;
    submitContactForm(name: string, email: string, phone: string, message: string): Promise<void>;
    updateFacultyMember(id: bigint, name: string, designation: string, qualification: string, department: string, bio: string): Promise<void>;
    updateNewsEvent(id: bigint, title: string, description: string, category: NewsEventCategory, isActive: boolean): Promise<void>;
    updateProgram(id: bigint, name: string, duration: string, description: string, eligibility: string, isActive: boolean): Promise<void>;
}
import type { NewsEvent as _NewsEvent, NewsEventCategory as _NewsEventCategory, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addFacultyMember(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFacultyMember(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFacultyMember(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addNewsEvent(arg0: string, arg1: string, arg2: NewsEventCategory, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addNewsEvent(arg0, arg1, to_candid_NewsEventCategory_n1(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNewsEvent(arg0, arg1, to_candid_NewsEventCategory_n1(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async addProgram(arg0: string, arg1: string, arg2: string, arg3: string, arg4: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProgram(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProgram(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async getActiveNewsEvents(): Promise<Array<NewsEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveNewsEvents();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveNewsEvents();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActivePrograms(): Promise<Array<Program>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivePrograms();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivePrograms();
            return result;
        }
    }
    async getAllFacultyMembers(): Promise<Array<FacultyMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFacultyMembers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFacultyMembers();
            return result;
        }
    }
    async getAllNewsEvents(): Promise<Array<NewsEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNewsEvents();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNewsEvents();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPrograms(): Promise<Array<Program>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPrograms();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPrograms();
            return result;
        }
    }
    async getFacultyMember(arg0: bigint): Promise<FacultyMember> {
        if (this.processError) {
            try {
                const result = await this.actor.getFacultyMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFacultyMember(arg0);
            return result;
        }
    }
    async getNewsEvent(arg0: bigint): Promise<NewsEvent> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewsEvent(arg0);
                return from_candid_NewsEvent_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewsEvent(arg0);
            return from_candid_NewsEvent_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProgram(arg0: bigint): Promise<Program> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgram(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgram(arg0);
            return result;
        }
    }
    async removeFacultyMember(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFacultyMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFacultyMember(arg0);
            return result;
        }
    }
    async removeNewsEvent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeNewsEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeNewsEvent(arg0);
            return result;
        }
    }
    async removeProgram(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeProgram(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeProgram(arg0);
            return result;
        }
    }
    async submitAdmissionInquiry(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAdmissionInquiry(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAdmissionInquiry(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async submitContactForm(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateFacultyMember(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFacultyMember(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFacultyMember(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateNewsEvent(arg0: bigint, arg1: string, arg2: string, arg3: NewsEventCategory, arg4: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNewsEvent(arg0, arg1, arg2, to_candid_NewsEventCategory_n1(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNewsEvent(arg0, arg1, arg2, to_candid_NewsEventCategory_n1(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async updateProgram(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProgram(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProgram(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
}
function from_candid_NewsEventCategory_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NewsEventCategory): NewsEventCategory {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_NewsEvent_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NewsEvent): NewsEvent {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    date: _Timestamp;
    description: string;
    isActive: boolean;
    category: _NewsEventCategory;
}): {
    id: bigint;
    title: string;
    date: Timestamp;
    description: string;
    isActive: boolean;
    category: NewsEventCategory;
} {
    return {
        id: value.id,
        title: value.title,
        date: value.date,
        description: value.description,
        isActive: value.isActive,
        category: from_candid_NewsEventCategory_n6(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    news: null;
} | {
    event: null;
}): NewsEventCategory {
    return "news" in value ? NewsEventCategory.news : "event" in value ? NewsEventCategory.event : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NewsEvent>): Array<NewsEvent> {
    return value.map((x)=>from_candid_NewsEvent_n4(_uploadFile, _downloadFile, x));
}
function to_candid_NewsEventCategory_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewsEventCategory): _NewsEventCategory {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewsEventCategory): {
    news: null;
} | {
    event: null;
} {
    return value == NewsEventCategory.news ? {
        news: null
    } : value == NewsEventCategory.event ? {
        event: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
